import Head from "next/head";
import { Barlow } from "@next/font/google";

const barlow = Barlow({
  weight: ["900"],
  subsets: ["latin"],
  style: ["italic"],
  display: "swap",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={barlow.className}>BLOGISH</h1>
      <h1 className={barlow.className}>BLOG APPLICATION</h1>
    </>
  );
}
